// src/constants/trainingsData.ts

export interface TrainingCourse {
  id: string;
  title: string;
  instructor: string;
  duration: string;
  level: "Beginner" | "Intermediate" | "Advanced";
  category: "Cybersecurity" | "Robotics & Drones" | "AI" | "Creative Arts" | "Web & Tech" | "Business & Management" | "Languages";
  description: string;
  imageUrl: string;
  isCertification: boolean;
  enrollmentLink?: string;
  price?: string;
  parentId?: string;
}

export const trainingsData: TrainingCourse[] = [
  {
    id: "course-1",
    title: "Cybersecurity",
    instructor: "Security Architect",
    duration: "3 months",
    level: "Intermediate",
    category: "Cybersecurity",
    description: "Establish a comprehensive security posture. Learn networking fundamentals, defense strategies, vulnerability management, and professional security frameworks.",
    imageUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 48,999",
  },
  {
    id: "course-2",
    title: "Ethical Hacking",
    instructor: "Offensive Security Expert",
    duration: "2 months",
    level: "Advanced",
    category: "Cybersecurity",
    description: "Master penetration testing, vulnerability scanning, and offensive security methodologies to identify and mitigate critical system flaws.",
    imageUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 34,999",
  },
  {
    id: "course-3",
    title: "Digital Forensics",
    instructor: "Forensics Specialist",
    duration: "2 months",
    level: "Intermediate",
    category: "Cybersecurity",
    description: "Investigate digital crimes, retrieve and analyze electronic evidence, and learn advanced methods of incident response and data recovery.",
    imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 32,999",
  },
  {
    id: "course-4",
    title: "Network Security",
    instructor: "Infrastructure Engineer",
    duration: "2 months",
    level: "Beginner",
    category: "Cybersecurity",
    description: "Protect network assets. Learn router and switch security, firewall configuration, secure communication channels, and encryption protocols.",
    imageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 32,999",
  },
  {
    id: "course-5",
    title: "Robotics Full Program",
    instructor: "Principal Robotics Engineer",
    duration: "6 months",
    level: "Advanced",
    category: "Robotics & Drones",
    description: "An intensive 6-month journey into robotics. Covers electronic foundations, embedded systems, microcontrollers, advanced sensors, and autonomous locomotion.",
    imageUrl: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 85,999",
  },
  {
    id: "course-6",
    title: "Robotics Foundation",
    instructor: "Robotics Instructor",
    duration: "2 months",
    level: "Beginner",
    category: "Robotics & Drones",
    description: "Start building your first robots. Learn basic electronics, microcontrollers (Arduino), sensor integration, and basic circuit programming.",
    imageUrl: "https://images.unsplash.com/photo-1563770660941-20978e870e26?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 31,999",
    parentId: "course-5",
  },
  {
    id: "course-7",
    title: "Robotics Advance",
    instructor: "Mechatronics Engineer",
    duration: "2 months",
    level: "Intermediate",
    category: "Robotics & Drones",
    description: "Advance your robotics skills. Work with kinematics, actuator control, feedback loops, and design complex robot configurations.",
    imageUrl: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 34,999",
    parentId: "course-5",
  },
  {
    id: "course-8",
    title: "Robotics Specialist",
    instructor: "Automation Specialist",
    duration: "2 months",
    level: "Advanced",
    category: "Robotics & Drones",
    description: "Specialized training in robotic automation, industrial arms, ROS (Robot Operating System), and smart autonomous pathfinding.",
    imageUrl: "https://images.unsplash.com/photo-1531747118685-ca8fa6e08806?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 37,999",
    parentId: "course-5",
  },
  {
    id: "course-9",
    title: "Drone Making Full Program",
    instructor: "Aeronautical Engineer",
    duration: "6 months",
    level: "Advanced",
    category: "Robotics & Drones",
    description: "Master the design, assembly, calibration, and pilotry of unmanned aerial vehicles (UAVs) from structural physics to advanced flight controllers.",
    imageUrl: "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 99,999",
  },
  {
    id: "course-10",
    title: "Drone Making Foundation",
    instructor: "UAV Flight Lead",
    duration: "2 months",
    level: "Beginner",
    category: "Robotics & Drones",
    description: "Learn the fundamentals of drone systems: propulsion, frames, ESCs, remote control protocols, and basic flight stabilization principles.",
    imageUrl: "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 35,999",
    parentId: "course-9",
  },
  {
    id: "course-11",
    title: "Drone Making Advance",
    instructor: "UAV Systems Architect",
    duration: "2 months",
    level: "Intermediate",
    category: "Robotics & Drones",
    description: "Build advanced quadcopters. Understand GPS integration, telemetry modules, camera gimbals, and automated waypoint navigation.",
    imageUrl: "https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 37,999",
    parentId: "course-9",
  },
  {
    id: "course-12",
    title: "Drone Making Specialist",
    instructor: "UAV Integration Engineer",
    duration: "2 months",
    level: "Advanced",
    category: "Robotics & Drones",
    description: "Specialize in custom drone configurations, autonomous mission programming, obstacles avoidance sensors, and thermal imaging payloads.",
    imageUrl: "https://images.unsplash.com/photo-1507682531662-421b17ac4f83?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 39,999",
    parentId: "course-9",
  },
  {
    id: "course-13",
    title: "AI Full Program",
    instructor: "AI Research Lead",
    duration: "4 months",
    level: "Advanced",
    category: "AI",
    description: "A comprehensive 4-month mastery of AI systems. Covers generative models, agentic workflows, deep learning algorithms, and real-world deployment.",
    imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 124,999",
  },
  {
    id: "course-14",
    title: "AI Automation",
    instructor: "Automation Engineer",
    duration: "2 months",
    level: "Intermediate",
    category: "AI",
    description: "Integrate LLMs and AI services into daily workflows and applications. Learn automation tools, database synchronization, and script orchestration.",
    imageUrl: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 34,999",
    parentId: "course-13",
  },
  {
    id: "course-15",
    title: "AI Agents",
    instructor: "AI Solutions Architect",
    duration: "2 months",
    level: "Advanced",
    category: "AI",
    description: "Build autonomous agents capable of planning, utilizing external tools, interacting with databases, and reasoning through multi-turn tasks.",
    imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 31,999",
    parentId: "course-13",
  },
  {
    id: "course-16",
    title: "AI Generatives",
    instructor: "Generative AI Specialist",
    duration: "2 months",
    level: "Beginner",
    category: "AI",
    description: "Leverage generative AI models. Master prompt engineering, vector databases, RAG systems, and integrating AI API models into interfaces.",
    imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 32,999",
    parentId: "course-13",
  },
  {
    id: "course-17",
    title: "Deep / Machine Learning",
    instructor: "ML Research Scientist",
    duration: "2 months",
    level: "Advanced",
    category: "AI",
    description: "Train and optimize deep neural networks. Master PyTorch/TensorFlow, supervised and unsupervised learning models, and computer vision systems.",
    imageUrl: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 40,999",
    parentId: "course-13",
  },
  {
    id: "course-18",
    title: "Arts Specialist Program",
    instructor: "Master Visual Artist",
    duration: "4 months",
    level: "Advanced",
    category: "Creative Arts",
    description: "A premium 4-month path to professional art. Develop your artistic voice across traditional mediums, digital illustrations, and portfolio building.",
    imageUrl: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 84,999",
  },
  {
    id: "course-19",
    title: "Arts Basics",
    instructor: "Fine Arts Instructor",
    duration: "2 months",
    level: "Beginner",
    category: "Creative Arts",
    description: "Learn the core foundations of visual arts: perspective, anatomy, color theory, shading, and introductory drawing techniques.",
    imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 24,999",
    parentId: "course-18",
  },
  {
    id: "course-20",
    title: "Arts Intermediate",
    instructor: "Digital Illustrator",
    duration: "2 months",
    level: "Intermediate",
    category: "Creative Arts",
    description: "Enhance your skills with complex compositions, advanced color theory, mixed media, and digital art platforms like Procreate/Photoshop.",
    imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 32,999",
    parentId: "course-18",
  },
  {
    id: "course-21",
    title: "Arts Professional",
    instructor: "Art Director",
    duration: "2 months",
    level: "Advanced",
    category: "Creative Arts",
    description: "Refine professional illustrations, character design, visual storytelling, and commercial branding work for games and media.",
    imageUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 39,999",
    parentId: "course-18",
  },
  {
    id: "course-22",
    title: "Blockchaining",
    instructor: "Blockchain Engineer",
    duration: "2 months",
    level: "Advanced",
    category: "Web & Tech",
    description: "Build decentralized protocols. Master Solidity, Ethereum architecture, smart contract security, Web3 APIs, and decentralized finance (DeFi).",
    imageUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 48,999",
  },
  {
    id: "course-23",
    title: "Digital Marketing",
    instructor: "Marketing Strategist",
    duration: "3 months",
    level: "Beginner",
    category: "Business & Management",
    description: "Drive brand growth. Master SEO, paid advertising (Google & Meta Ads), search engine marketing, content strategies, and web analytics.",
    imageUrl: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 42,999",
  },
  {
    id: "course-24",
    title: "Financial Literacy",
    instructor: "Financial Consultant",
    duration: "2 months",
    level: "Beginner",
    category: "Business & Management",
    description: "Gain absolute control over finance. Learn bookkeeping, personal finance management, investment vehicles, and standard corporate accounting.",
    imageUrl: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 32,999",
  },
  {
    id: "course-25",
    title: "Web & App Development",
    instructor: "Senior Solutions Engineer",
    duration: "3 months",
    level: "Intermediate",
    category: "Web & Tech",
    description: "Build high-performance web and mobile apps. Learn modern JavaScript frameworks, responsive layouts, API integration, and database systems.",
    imageUrl: "https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 47,999",
  },
  {
    id: "course-26",
    title: "IELTS",
    instructor: "IELTS Master Trainer",
    duration: "2 months",
    level: "Intermediate",
    category: "Languages",
    description: "Comprehensive IELTS exam preparation. Target 8.0+ Band with intensive practice in Listening, Reading, Writing, and Speaking modules.",
    imageUrl: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 32,999",
  },
  {
    id: "course-27",
    title: "PTA (PTE Academic Prep)",
    instructor: "PTE Expert Coach",
    duration: "2 months",
    level: "Intermediate",
    category: "Languages",
    description: "Master the Pearson Test of English Academic (PTE). Learn computer-graded strategies, speech response templates, and score-maximizing hacks.",
    imageUrl: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 29,999",
  },
  {
    id: "course-28",
    title: "HR Through AI",
    instructor: "AI HR Innovator",
    duration: "2 months",
    level: "Intermediate",
    category: "Business & Management",
    description: "Transform human resource workflows using AI tools. Automate resume screening, talent sourcing, performance evaluations, and employee onboarding.",
    imageUrl: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 44,999",
  },
  {
    id: "course-29",
    title: "Cloud Computing",
    instructor: "Cloud Solutions Architect",
    duration: "2 months",
    level: "Intermediate",
    category: "Web & Tech",
    description: "Build scalable cloud infrastructure. Master AWS, Google Cloud Platform, Docker, Kubernetes, CI/CD pipelines, and cloud security architectures.",
    imageUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 41,999",
  },
  {
    id: "course-30",
    title: "Taxation & Legal Compliance",
    instructor: "Tax Consultant & Advocate",
    duration: "2 months",
    level: "Intermediate",
    category: "Business & Management",
    description: "Master corporate tax filings, legal structures, income tax laws, sales tax registration, and comprehensive financial compliance procedures.",
    imageUrl: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 34,999",
  },
  {
    id: "course-31",
    title: "Game Development",
    instructor: "Senior Game Developer",
    duration: "2 months",
    level: "Intermediate",
    category: "Web & Tech",
    description: "Build your first video games. Master Unity or Unreal Engine, C# scripting, 3D/2D physics, lighting assets, and game publishing platforms.",
    imageUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&h=400&fit=crop&auto=format",
    isCertification: true,
    enrollmentLink: "#enroll",
    price: "PKR 61,999",
  },
];
